app/models.py
from extensions import db
from flask import current_app
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from extensions import login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin, AnonymousUserMixin
from datetime import datetime

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20))
    password = db.Column(db.String(20))
    email = db.Column(db.String(40))
    confirmed = db.Column(db.BOOLEAN, default=False)
    password_hash = db.Column(db.String(128))
    name = db.Column(db.String(64))
    location = db.Column(db.String(64))
    about_me = db.Column(db.Text())
    member_since = db.Column(db.DateTime(), default=datetime.utcnow)
    last_seen = db.Column(db.DateTime(), default=datetime.utcnow)
    posts = db.relationship('Post', backref='author', lazy='dynamic')

    def ping(self):
        self.last_seen = datetime.utcnow()
        db.session.add(self)

    @property
    def password(self):
        raise AttributeError('密码属性不可读')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id})

    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return '激活失败'
        if data.get('confirm') != self.id:
            return '激活失败'
        self.confirmed = True
        db.session.add(self)
        return '激活成功'


class AnonymousUser(AnonymousUserMixin):
    def can(self, permissions):
        return False
    def is_administrator(self):
        return False

login_manager.anonymous_user = AnonymousUser

class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))





@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import Length, EqualTo, Email, DataRequired


class RegistrationForm(FlaskForm):
    username = StringField('用户名', validators=[Length(3, 10, '用户名必须在6到10个字符之间')])
    password = PasswordField('密码', validators=[Length(3, 10, '密码必须在6到10个字符之间'), EqualTo('password2', '两次输入的密码不一致，请重新输入')])
    password2 = PasswordField('确认密码', validators=[Length(3, 10, '密码必须在6到10个字符之间')])
    email = StringField('邮箱', validators=[Email(), Length(1, 30, '邮箱必须在1到30个字符之间')])
    submit = SubmitField('立即注册')


class LoginForm(FlaskForm):
    email = StringField('邮箱', validators=[Email(), Length(1, 30, '邮箱必须在1到30个字符之间')])
    password = PasswordField('密码', validators=[Length(3, 10, '密码必须在6到10个字符之间')])
    remember_me = BooleanField('保持登录')
    submit = SubmitField('登录')


class EditProfileForm(FlaskForm):
    name = StringField('Real name', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0, 64)])
    about_me = TextAreaField('About me')
    submit = SubmitField('Submit')


class PostForm(FlaskForm):
    body = TextAreaField("What's on your mind?", validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from app.config import config
from extensions import config_extensions
from app.views import register_blueprint

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config.get(config_name or 'default'))
    config_extensions(app)
    register_blueprint(app)
    return app

app/views/__init__.py
from .mains import mains
from .users import users

DEFAULT_BLUEPRINT = (
    (mains, ''),
    (users, '/user/')
)


def register_blueprint(app):
    for blueprint, url_prefix in DEFAULT_BLUEPRINT:
        app.register_blueprint(blueprint, url_prefix=url_prefix)

app/views/mains.py
from flask import Blueprint, render_template,request, flash, url_for, redirect, current_app
from flask_login import login_required, current_user
from app.forms import EditProfileForm, PostForm
from extensions import db
from app.models import Post


mains = Blueprint('main', __name__)


@mains.route('/', methods=['GET','POST'])
def index():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(body=form.body.data, author=current_user._get_current_object())
        db.session.add(post)
        return redirect(url_for('main.index'))
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    return render_template('common/index.html', form=form, posts=posts,
                           pagination=pagination)



@mains.route('/secret/')
@login_required
def secret():
    return '只有登录用户可访问'


@mains.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user)
        flash('Your profile has been updated.')
        return redirect(url_for('user.profile', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('user/edit_profile.html', form=form)

app/views/users.py
from flask import Blueprint, render_template, flash, redirect, request,url_for, abort
from app.forms import RegistrationForm, LoginForm
from app.email import send_mail
from app.models import User
from flask_login import login_user,login_required,logout_user,current_user
from extensions import db
from app.models import Post


users = Blueprint('user', __name__)

@users.route('/login/', methods = ['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.verify_password(form.password.data):
            login_user(user, form.remember_me.data)
            return redirect(request.args.get('next') or url_for('main.index'))
        flash('用户名或密码无效')
    return render_template('user/login.html', form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('main.index'))


@users.route('/register/', methods = ['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        token = user.generate_confirmation_token()
        send_mail('账号激活', form.email.data, 'email/activate.html', user=user, token=token)
        flash('点击链接激活')
        return redirect(request.args.get('next') or url_for('main.index'))
    return render_template('user/register.html', form=form)


@users.route('/activate/<token>')
@login_required
def activate(token):
    if current_user.confirmed():
        return redirect(url_for('main.index'))
    if current_user.confirm(token):
        flash('激活成功')
    else:
        flash('激活失败')
        return redirect(url_for('main.index'))


@login_required
@users.route('/profile/<username>')
def profile(username):
    username = User.query.filter_by(username=username).first()
    if username is None:
        abort(404)
    posts = username.posts.order_by(Post.timestamp.desc()).all()
    return render_template('user/profile.html', username=username, posts=posts)

#修改头像
@login_required
@users.route('/icon/')
def icon():
    return render_template('user/icon.html')



# @users.before_app_request
# def before_request():
#     if current_user.is_authenticated:
#         current_user.ping()
#         if not current_user.confirmed \
#                 and request.endpoint[:5] != 'user.':
#             return redirect(url_for('user.unconfirmed'))

#
# @users.route('/unconfirmed/')
# def unconfirmed():
#     if current_user.is_anonymous or current_user.confirmed:
#         return redirect(url_for('main.index'))
#     return render_template('user/unconfirmed.html')

app/templates/common/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
    <ul class="pagination">
        <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
            <a href="{% if pagination.has_prev %}{{ url_for(endpoint,
page = pagination.page - 1, **kwargs) }}{% else %}#{% endif %}">
                &laquo;
            </a>
        </li>
        {% for p in pagination.iter_pages() %}
            {% if p %}
                {% if p == pagination.page %}
                    <li class="active">
                        <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="disabled"><a href="#">&hellip;</a></li>
            {% endif %}
        {% endfor %}
        <li{% if not pagination.has_next %} class="disabled"{% endif %}>
            <a href="{% if pagination.has_next %}{{ url_for(endpoint,
page = pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">
                &raquo;
            </a>
        </li>
    </ul>
{% endmacro %}

app/templates/common/_post.html
<ul class="posts">
    {% for post in posts %}
        <li class="post">
            <div class="profile-thumbnail">
                <a href="{{ url_for('.user', username=post.author.username) }}">
                    <img class="img-rounded profile-thumbnail"
                         src="{{ post.author.gravatar(size=40) }}">
                </a>
            </div>

            <div class="post-date">{{ moment(post.timestamp).fromNow() }}</div>
            <div class="post-author">
                <a href="{{ url_for('.user', username=post.author.username) }}">
                    {{ post.author.username }}
                </a>
            </div>
            <div class="post-body">{{ post.body }}</div>
        </li>
    {% endfor %}
</ul>

app/templates/common/base.html
{# 继承自bootstrap的基础模板 #}
{% extends 'bootstrap/base.html' %}
{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}
{% import "common/_macros.html" as macros %}

{# 定制导航条 #}
{% block navbar %}
    <nav class="navbar navbar-inverse" style="border-radius: 0px;">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target=".navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">首页</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#">版块一</a></li>
                    <li><a href="#">版块二</a></li>
                    <li><a href="#">版块三</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('user.logout') }}">退出登录</a></li>
                        <li><a href="{{ url_for('user.profile', username=current_user.username) }}">{{ current_user.username }}</a></li>
                        {% else %}
                        <li><a href="{{ url_for('user.login') }}">登录</a></li>
                        <li><a href="{{ url_for('user.register') }}">注册</a></li>
                        {% endif %}

                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
{% endblock %}

{# 定制内容 #}
{% block content %}
    <div class="container">
        {% block page_content %}

    <div class="container">

        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}

    </div>
        {% endblock %}
    </div>
{% endblock %}

{# 加载收藏夹图标 #}
{% block head %}
    {{ super() }}
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}" />
{% endblock %}

app/templates/common/index.html
{% extends "common/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "common/_macros.html" as macros %}
{% block content %}
<div>
        {{ wtf.quick_form(form) }}
</div>

{% include 'common/_post.html' %}
    <div class="pagination">
        {{ macros.pagination_widget(pagination, 'main.index') }}
    </div>
{% endblock %}

app/templates/user/edit_profile.html
{% extends 'common/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title %}资料修改{% endblock %}

app/templates/user/icon.html
<h1>icon</h1>

app/templates/user/login.html
{% extends 'common/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title %}用户登录{% endblock %}

{% block page_content %}
    <h1>欢迎登录...</h1>
    <div class="col-md-4">

        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

{# 引入css文件 #}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/common.css') }}">
{% endblock %}

{# 加载JS文件 #}
{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='js/common.js') }}"></script>
{% endblock %}

app/templates/user/profile.html
{% extends 'common/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title %}资料修改{% endblock %}

{% block page_content %}
    <div class="page-header">
        <h1>{{ username.username }}</h1>
        {% if username.name or username.location %}
            <p>
                {% if username.name %}{{ username.name }}{% endif %}
                {% if username.location %}
                    From <a href="http://maps.google.com/?q={{ username.location }}">
                    {{ username.location }}
                </a>
                {% endif %}
            </p>
        {% endif %}
{#        {% if current_user.is_administrator() %}#}
{#            <p><a href="mailto:{{ username.email }}">{{ username.email }}</a></p>#}
{#        {% endif %}#}
        {% if username.about_me %}<p>{{ username.about_me }}</p>{% endif %}
        <p>
            Member since {{ moment(username.member_since).format('L') }}.
            Last seen {{ moment(username.last_seen).fromNow() }}.
        </p>
        {% if user == current_user %}
        <a class="btn btn-default" href="{{ url_for('mains.edit_profile') }}">
        Edit Profile
        </a>

        <h3>Posts by {{ user.username }}</h3>
        {% include 'common/_post.html' %}
        <div class="pagination">
        {{ macros.pagination_widget(pagination, 'main.index') }}
        </div>
        {% endif %}
    </div>
{% endblock %}

app/templates/user/register.html
{% extends 'common/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title %}用户登录{% endblock %}

{% block page_content %}
    <h1>欢迎注册...</h1>



    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>


{% endblock %}


{# 引入css文件 #}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/common.css') }}">
{% endblock %}

{# 加载JS文件 #}
{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='js/common.js') }}"></script>
{% endblock %}

app/templates/user/unconfirmed.html
<h1>unconfirmed</h1>